const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

// Convert SVG to PNG for iOS (if convert-favicon.js exists)
try {
  if (fs.existsSync(path.join(__dirname, 'convert-favicon.js'))) {
    execSync('node convert-favicon.js', { stdio: 'inherit' });
  }
} catch (error) {
  console.warn('Warning: Could not convert favicon to PNG:', error.message);
  console.warn('Continuing with build...');
}

// Read the HTML, JS, and favicon files
let htmlContent = fs.readFileSync(path.join(__dirname, 'public', 'index.html'), 'utf8');
const jsContent = fs.readFileSync(path.join(__dirname, 'public', 'app.js'), 'utf8');
const faviconContent = fs.readFileSync(path.join(__dirname, 'public', 'favicon.svg'), 'utf8');
const appleTouchIconContent = fs.readFileSync(path.join(__dirname, 'public', 'apple-touch-icon.png'));

// Generate a hash of the SVG content for cache-busting
// This ensures the icon URL changes automatically when the icon is modified
const svgHash = crypto.createHash('md5').update(faviconContent).digest('hex').substring(0, 8);

// Update the HTML to include the version parameter in the apple-touch-icon URL
htmlContent = htmlContent.replace(
  /href="\/apple-touch-icon\.png"/,
  `href="/apple-touch-icon.png?v=${svgHash}"`
);

// Convert PNG to base64 for embedding
const appleTouchIconBase64 = appleTouchIconContent.toString('base64');

// Create the worker file with embedded content
const workerContent = `// This file is auto-generated by build.js
const HTML_CONTENT = ${JSON.stringify(htmlContent)};
const JS_CONTENT = ${JSON.stringify(jsContent)};
const FAVICON_CONTENT = ${JSON.stringify(faviconContent)};
const APPLE_TOUCH_ICON_BASE64 = ${JSON.stringify(appleTouchIconBase64)};

const POLLEN_CURRENT_PARAMS = 'us_aqi,pm10,pm2_5,ozone,nitrogen_dioxide,sulphur_dioxide,carbon_monoxide,alder_pollen,birch_pollen,grass_pollen,weed_pollen,mugwort_pollen,olive_pollen,ragweed_pollen';
const POLLEN_HOURLY_PARAMS = 'alder_pollen,birch_pollen,grass_pollen,weed_pollen,mugwort_pollen,olive_pollen,ragweed_pollen';

function jsonResponse(data, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      ...extraHeaders,
    },
  });
}

function hasNumericValue(value) {
  return value !== null && value !== undefined && Number.isFinite(Number(value));
}

function googleIndexToPollenValue(indexValue) {
  // Google Pollen API returns an index (typically 0-5), not grains/m³.
  // Scale it into the app's existing pollen value shape so the current UI and
  // allergy-risk code can continue to represent unavailable values as null.
  if (!hasNumericValue(indexValue)) return null;
  return Math.max(0, Number(indexValue)) * 50;
}

function maxAvailableGoogleValue(values) {
  const availableValues = values.filter(hasNumericValue).map(Number);
  if (availableValues.length === 0) return null;
  return Math.max(...availableValues);
}

function normalizeGoogleCode(value) {
  return String(value || '').trim().toUpperCase();
}

function getGooglePollenTypeCode(info) {
  return normalizeGoogleCode(info?.code || info?.typeCode || info?.pollenType || info?.displayName);
}

function getGooglePlantCode(info) {
  return normalizeGoogleCode(info?.code || info?.plantCode || info?.displayName);
}

function googleInfoHasUsableIndex(info) {
  return info?.inSeason !== false && info?.indexInfo && hasNumericValue(info.indexInfo.value);
}

function googleInfoIsPresentWithoutIndex(info) {
  return info && !info.indexInfo;
}

function typeCodeToAppField(typeCode) {
  const normalized = normalizeGoogleCode(typeCode);
  if (normalized === 'TREE') return 'tree';
  if (normalized === 'GRASS') return 'grass';
  if (normalized === 'WEED') return 'weed';
  return null;
}

function plantCodeToAppField(plantCode) {
  const normalized = normalizeGoogleCode(plantCode);
  const plantMap = {
    ALDER: 'alder_pollen',
    BIRCH: 'birch_pollen',
    OLIVE: 'olive_pollen',
    GRAMINALES: 'grass_pollen',
    GRASS: 'grass_pollen',
    RAGWEED: 'ragweed_pollen',
    MUGWORT: 'mugwort_pollen',
  };
  return plantMap[normalized] || null;
}

function normalizeGooglePollen(googleData) {
  const dailyInfo = Array.isArray(googleData?.dailyInfo) ? googleData.dailyInfo : [];
  if (dailyInfo.length === 0) return null;

  const hourly = {
    time: [],
    alder_pollen: [],
    birch_pollen: [],
    olive_pollen: [],
    grass_pollen: [],
    weed_pollen: [],
    mugwort_pollen: [],
    ragweed_pollen: [],
  };

  let current = null;
  const noneDisplayHourly = [];

  for (const day of dailyInfo.slice(0, 5)) {
    const date = day.date
      ? [day.date.year, String(day.date.month).padStart(2, '0'), String(day.date.day).padStart(2, '0')].join('-')
      : new Date().toISOString().split('T')[0];
    const categoryValues = { tree: null, grass: null, weed: null };
    const noneDisplayFields = {};

    for (const info of (day.pollenTypeInfo || [])) {
      const field = typeCodeToAppField(getGooglePollenTypeCode(info));
      if (!field) continue;
      if (field === 'weed' && googleInfoIsPresentWithoutIndex(info)) {
        noneDisplayFields.weed_pollen = true;
      }
      if (!googleInfoHasUsableIndex(info)) continue;
      const value = googleIndexToPollenValue(info.indexInfo.value);
      if (hasNumericValue(value)) {
        categoryValues[field] = categoryValues[field] === null ? value : Math.max(categoryValues[field], value);
      }
    }

    const plantValues = {
      alder_pollen: null,
      birch_pollen: null,
      olive_pollen: null,
      grass_pollen: null,
      weed_pollen: null,
      mugwort_pollen: null,
      ragweed_pollen: null,
    };

    for (const info of (day.plantInfo || [])) {
      const field = plantCodeToAppField(getGooglePlantCode(info));
      if (!field) continue;
      if ((field === 'weed_pollen' || field === 'ragweed_pollen') && googleInfoIsPresentWithoutIndex(info)) {
        noneDisplayFields[field] = true;
      }
      if (!googleInfoHasUsableIndex(info)) continue;
      const value = googleIndexToPollenValue(info.indexInfo.value);
      if (hasNumericValue(value)) {
        plantValues[field] = plantValues[field] === null ? value : Math.max(plantValues[field], value);
      }
    }

    plantValues.weed_pollen = categoryValues.weed;

    const normalizedDay = {
      alder_pollen: plantValues.alder_pollen ?? categoryValues.tree,
      birch_pollen: plantValues.birch_pollen ?? categoryValues.tree,
      olive_pollen: plantValues.olive_pollen ?? categoryValues.tree,
      grass_pollen: plantValues.grass_pollen ?? categoryValues.grass,
      weed_pollen: plantValues.weed_pollen,
      mugwort_pollen: plantValues.mugwort_pollen,
      ragweed_pollen: plantValues.ragweed_pollen,
    };

    for (const field of Object.keys(noneDisplayFields)) {
      if (hasNumericValue(normalizedDay[field])) {
        delete noneDisplayFields[field];
      }
    }

    if (!current) {
      current = {
        us_aqi: null,
        pm10: null,
        pm2_5: null,
        ozone: null,
        nitrogen_dioxide: null,
        sulphur_dioxide: null,
        carbon_monoxide: null,
        ...normalizedDay,
      };
    }
    noneDisplayHourly.push(noneDisplayFields);

    hourly.time.push(date + 'T12:00');
    for (const field of POLLEN_HOURLY_PARAMS.split(',')) {
      hourly[field].push(normalizedDay[field]);
    }
  }

  return {
    latitude: googleData.regionCode ? undefined : googleData.latitude,
    longitude: googleData.longitude,
    current,
    hourly,
    pollen_null_display_as_none: {
      current: noneDisplayHourly[0] || {},
      hourly: noneDisplayHourly,
    },
    pollen_source: 'google',
    pollen_units: 'Google index scaled to app pollen value range',
  };
}

function tomorrowIndexToPollenValue(indexValue) {
  // Tomorrow.io pollen indexes are ordinal values (0-5). Keep the same scaling
  // used for Google so mixed-source payloads stay in the app's expected range.
  if (!hasNumericValue(indexValue)) return null;
  return Math.max(0, Number(indexValue)) * 50;
}

function normalizeTomorrowPollen(tomorrowData) {
  const intervals = Array.isArray(tomorrowData?.data?.timelines?.[0]?.intervals)
    ? tomorrowData.data.timelines[0].intervals
    : Array.isArray(tomorrowData?.timelines?.daily)
      ? tomorrowData.timelines.daily.map(day => ({ startTime: day.time, values: day.values }))
      : [];
  if (intervals.length === 0) return null;

  const hourly = {
    time: [],
    alder_pollen: [],
    birch_pollen: [],
    olive_pollen: [],
    grass_pollen: [],
    weed_pollen: [],
    mugwort_pollen: [],
    ragweed_pollen: [],
  };

  let current = null;
  for (const interval of intervals.slice(0, 5)) {
    const values = interval.values || {};
    const normalizedDay = {
      alder_pollen: null,
      birch_pollen: null,
      olive_pollen: null,
      grass_pollen: tomorrowIndexToPollenValue(values.grassIndex),
      weed_pollen: tomorrowIndexToPollenValue(values.weedIndex),
      mugwort_pollen: null,
      ragweed_pollen: null,
    };

    if (!current) {
      current = {
        us_aqi: null,
        pm10: null,
        pm2_5: null,
        ozone: null,
        nitrogen_dioxide: null,
        sulphur_dioxide: null,
        carbon_monoxide: null,
        ...normalizedDay,
      };
    }

    hourly.time.push(interval.startTime || new Date().toISOString());
    for (const field of POLLEN_HOURLY_PARAMS.split(',')) {
      hourly[field].push(normalizedDay[field]);
    }
  }

  return {
    current,
    hourly,
    pollen_source: 'tomorrow',
    pollen_units: 'Tomorrow.io index scaled to app pollen value range',
  };
}

async function fetchTomorrowPollen(lat, lon, apiKey) {
  if (!apiKey) return null;
  const location = encodeURIComponent(lat + ',' + lon);
  const forecastUrl = \`https://api.tomorrow.io/v4/weather/forecast?location=\${location}&timesteps=1d&units=metric&apikey=\${encodeURIComponent(apiKey)}\`;
  const forecastResponse = await fetch(forecastUrl);
  if (forecastResponse.ok) {
    const forecastData = normalizeTomorrowPollen(await forecastResponse.json());
    if (hasNumericValue(forecastData?.current?.weed_pollen) || hasNumericValue(forecastData?.current?.grass_pollen)) {
      return forecastData;
    }
  }

  const timelinesUrl = \`https://api.tomorrow.io/v4/timelines?location=\${location}&fields=grassIndex,weedIndex&timesteps=1d&units=metric&apikey=\${encodeURIComponent(apiKey)}\`;
  const timelinesResponse = await fetch(timelinesUrl);
  if (!timelinesResponse.ok) {
    throw new Error(\`Tomorrow.io pollen request failed with forecast status \${forecastResponse.status} and timelines status \${timelinesResponse.status}\`);
  }
  return normalizeTomorrowPollen(await timelinesResponse.json());
}

function mergeMissingPollen(primary, fallback, fallbackSource) {
  if (!primary?.current || !fallback?.current) return primary;
  let usedFallback = false;
  const merged = JSON.parse(JSON.stringify(primary));
  for (const field of POLLEN_HOURLY_PARAMS.split(',')) {
    if (!hasNumericValue(merged.current[field]) && hasNumericValue(fallback.current[field])) {
      merged.current[field] = fallback.current[field];
      usedFallback = true;
    }
    if (Array.isArray(merged.hourly?.[field]) && Array.isArray(fallback.hourly?.[field])) {
      for (let i = 0; i < merged.hourly[field].length; i++) {
        if (!hasNumericValue(merged.hourly[field][i]) && hasNumericValue(fallback.hourly[field][i])) {
          merged.hourly[field][i] = fallback.hourly[field][i];
          usedFallback = true;
        }
      }
    }
  }
  if (usedFallback) {
    merged.pollen_source = (primary.pollen_source || 'primary') + '+' + fallbackSource;
    merged.pollen_fallback_source = fallbackSource;
    merged.pollen_units = [primary.pollen_units, fallback.pollen_units].filter(Boolean).join('; ');
  }
  return merged;
}

async function fetchOpenMeteoPollen(lat, lon) {
  const openMeteoUrl = \`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=\${encodeURIComponent(lat)}&longitude=\${encodeURIComponent(lon)}&current=\${POLLEN_CURRENT_PARAMS}&hourly=\${POLLEN_HOURLY_PARAMS}&forecast_days=5&timezone=auto\`;
  const response = await fetch(openMeteoUrl, {
    headers: { 'User-Agent': 'WeatherApp/1.0 (https://weather-app.jackanglim3.workers.dev)' },
  });
  if (!response.ok) throw new Error(\`Open-Meteo pollen request failed with status \${response.status}\`);
  const data = await response.json();
  return { ...data, pollen_source: 'open-meteo' };
}

async function handlePollenRequest(url, env) {
  const lat = url.searchParams.get('lat') || url.searchParams.get('latitude');
  const lon = url.searchParams.get('lon') || url.searchParams.get('longitude');
  if (!lat || !lon) {
    return jsonResponse({ error: true, reason: 'Missing lat or lon parameters' }, 400);
  }

  if (env.GOOGLE_POLLEN_API_KEY) {
    try {
      // Google Maps Platform Pollen API daily forecast endpoint:
      // https://pollen.googleapis.com/v1/forecast:lookup
      const googleUrl = \`https://pollen.googleapis.com/v1/forecast:lookup?key=\${encodeURIComponent(env.GOOGLE_POLLEN_API_KEY)}&location.latitude=\${encodeURIComponent(lat)}&location.longitude=\${encodeURIComponent(lon)}&days=5&plantsDescription=false\`;
      const googleResponse = await fetch(googleUrl);
      if (googleResponse.ok) {
        const googleData = await googleResponse.json();
        const normalized = normalizeGooglePollen(googleData);
        if (normalized?.current) {
          if (!hasNumericValue(normalized.current.weed_pollen) || !hasNumericValue(normalized.current.ragweed_pollen)) {
            const firstDay = Array.isArray(googleData.dailyInfo) ? googleData.dailyInfo[0] : null;
            const pollenTypeSummary = (firstDay?.pollenTypeInfo || []).map(info => ({
              code: getGooglePollenTypeCode(info),
              inSeason: info.inSeason ?? null,
              hasIndexInfo: Boolean(info.indexInfo),
              indexValue: info.indexInfo?.value ?? null,
              category: info.indexInfo?.category ?? null,
            }));
            const plantSummary = (firstDay?.plantInfo || [])
              .filter(info => ['RAGWEED', 'MUGWORT'].includes(getGooglePlantCode(info)) || info?.plantDescription?.type === 'WEED')
              .map(info => ({
                code: getGooglePlantCode(info),
                type: info.plantDescription?.type ?? null,
                inSeason: info.inSeason ?? null,
                hasIndexInfo: Boolean(info.indexInfo),
                indexValue: info.indexInfo?.value ?? null,
                category: info.indexInfo?.category ?? null,
              }));
            console.warn('Google pollen weed/ragweed unavailable in first day', JSON.stringify({ pollenTypeSummary, plantSummary }));
          }
          return jsonResponse(normalized, 200, { 'X-Pollen-Source': normalized.pollen_source || 'google' });
        }
      } else {
        console.warn('Google Pollen API unavailable; falling back to Open-Meteo. Status:', googleResponse.status);
      }
    } catch (error) {
      console.warn('Google Pollen API failed; falling back to Open-Meteo:', error.message);
    }
  }

  if (env.TOMORROW_API_KEY) {
    try {
      const tomorrowData = await fetchTomorrowPollen(lat, lon, env.TOMORROW_API_KEY);
      if (tomorrowData?.current) {
        return jsonResponse(tomorrowData, 200, { 'X-Pollen-Source': tomorrowData.pollen_source || 'tomorrow' });
      }
    } catch (error) {
      console.warn('Tomorrow.io pollen fallback failed; falling back to Open-Meteo:', error.message);
    }
  }

  try {
    const openMeteoData = await fetchOpenMeteoPollen(lat, lon);
    return jsonResponse(openMeteoData, 200, { 'X-Pollen-Source': 'open-meteo' });
  } catch (error) {
    console.error('Open-Meteo pollen fallback failed:', error.message);
    return jsonResponse({ error: true, reason: 'Pollen data unavailable' }, 503);
  }
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    
    // Serve the HTML page
    if (url.pathname === '/' || url.pathname === '/index.html') {
      return new Response(HTML_CONTENT, {
        headers: {
          'Content-Type': 'text/html;charset=UTF-8',
        },
      });
    }
    
    // Serve the JavaScript file
    if (url.pathname === '/app.js') {
      return new Response(JS_CONTENT, {
        headers: {
          'Content-Type': 'application/javascript',
        },
      });
    }
    
    // Serve the favicon
    if (url.pathname === '/favicon.svg') {
      return new Response(FAVICON_CONTENT, {
        headers: {
          'Content-Type': 'image/svg+xml',
          'Cache-Control': 'public, max-age=31536000', // Cache for 1 year
        },
      });
    }
    
    // Serve the Apple touch icon (PNG for iOS)
    if (url.pathname === '/apple-touch-icon.png') {
      const pngBuffer = Uint8Array.from(atob(APPLE_TOUCH_ICON_BASE64), c => c.charCodeAt(0));
      return new Response(pngBuffer, {
        headers: {
          'Content-Type': 'image/png',
          'Cache-Control': 'public, max-age=31536000', // Cache for 1 year
        },
      });
    }
    
    // Proxy API requests to avoid CORS issues
    if (url.pathname.startsWith('/api/')) {
      const apiPath = url.pathname.replace('/api/', '');
      let targetUrl;
      
      if (apiPath.startsWith('pollen')) {
        return handlePollenRequest(url, env);
      }

      // Geocoding API uses a different base URL
      if (apiPath.startsWith('geocoding')) {
        // Convert /api/geocoding?name=... to geocoding-api.open-meteo.com/v1/search?name=...
        const searchParams = url.search;
        targetUrl = \`https://geocoding-api.open-meteo.com/v1/search\${searchParams}\`;
      } else if (apiPath.startsWith('reverse')) {
        // Reverse geocoding using BigDataCloud (free, no API key needed)
        // Extract lat and lon from query params
        const lat = url.searchParams.get('lat');
        const lon = url.searchParams.get('lon');
        if (lat && lon) {
          targetUrl = \`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=\${encodeURIComponent(lat)}&longitude=\${encodeURIComponent(lon)}&localityLanguage=en\`;
        } else {
          return new Response(JSON.stringify({ error: true, reason: 'Missing lat or lon parameters' }), {
            status: 400,
            headers: {
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*',
            },
          });
        }
      } else if (apiPath.startsWith('alerts')) {
        // National Weather Service alerts API (US only)
        // Remove /api/ prefix and construct the full NWS URL
        const nwsPath = apiPath; // apiPath is already "alerts/active/zone/..." or "alerts/active"
        targetUrl = \`https://api.weather.gov/\${nwsPath}\${url.search}\`;
      } else if (apiPath.startsWith('nws-points')) {
        // NWS points API to get forecast zones
        const pathParts = apiPath.split('/');
        if (pathParts.length > 1) {
          targetUrl = \`https://api.weather.gov/points/\${pathParts.slice(1).join('/')}\`;
        } else {
          targetUrl = \`https://api.weather.gov/points\${url.search}\`;
        }
      } else if (apiPath.startsWith('nws-wms')) {
        // Proxy for NWS WMS service to handle CORS
        // Extract WMS parameters from query string
        const wmsParams = new URLSearchParams(url.search);
        // #region agent log
        const logData = {originalQuery:url.search,allParams:Object.fromEntries(wmsParams.entries()),hasTime:wmsParams.has('time'),timeValue:wmsParams.get('time')};
        // #endregion
        // Build the WMS GetMap request URL
        // Use RIDGE2 WMS endpoint - official NWS radar service
        const wmsBaseUrl = 'https://opengeo.ncep.noaa.gov/geoserver/ows';
        // Preserve all existing parameters (including time if present)
        wmsParams.set('service', 'WMS');
        wmsParams.set('request', 'GetMap');
        if (!wmsParams.has('version')) {
          wmsParams.set('version', '1.3.0');
        }
        if (!wmsParams.has('styles')) {
          wmsParams.set('styles', '');
        }
        targetUrl = \`\${wmsBaseUrl}?\${wmsParams.toString()}\`;
        // #region agent log
        const finalLogData = {targetUrl:targetUrl,finalParams:Object.fromEntries(wmsParams.entries()),hasTimeFinal:wmsParams.has('time'),timeValueFinal:wmsParams.get('time')};
        // #endregion
      } else {
        // Weather API uses the standard base URL
        targetUrl = \`https://api.open-meteo.com/v1/\${apiPath}\${url.search}\`;
      }
      
      try {
        let fetchOptions = {};
        // Add user agent for NWS (required by their usage policy)
        if (apiPath.startsWith('alerts') || apiPath.startsWith('nws-points') || apiPath.startsWith('nws-wms')) {
          const headers = new Headers();
          headers.set('User-Agent', 'WeatherApp/1.0 (contact@example.com)');
          fetchOptions = { headers };
        }
        
        // Special handling for NWS WMS - proxy images with CORS headers
        if (apiPath.startsWith('nws-wms')) {
          try {
            // #region agent log
            // Log the full request URL and all parameters for debugging
            const requestParams = {
              targetUrl: targetUrl,
              method: 'GET',
              hasTime: wmsParams.has('time'),
              timeValue: wmsParams.get('time'),
              allParams: Object.fromEntries(wmsParams.entries()),
              bbox: wmsParams.get('BBOX') || wmsParams.get('bbox'),
              crs: wmsParams.get('CRS') || wmsParams.get('crs'),
              layers: wmsParams.get('LAYERS') || wmsParams.get('layers')
            };
            console.error('NWS_WMS_PROXY_REQUEST', JSON.stringify(requestParams));
            // #endregion
            const response = await fetch(targetUrl, fetchOptions);
            
            // Get content type early
            const responseContentType = response.headers.get('Content-Type') || 'unknown';
            const responseIsImage = responseContentType.startsWith('image/');
            const responseIsXML = responseContentType.includes('xml') || responseContentType.includes('html');
            
            // #region agent log
            console.error('NWS_WMS_PROXY_RESPONSE', JSON.stringify({status:response.status,statusText:response.statusText,ok:response.ok,contentType:responseContentType,isImage:responseIsImage,isXML:responseIsXML,targetUrl:targetUrl}));
            // #endregion
            
            if (!response.ok) {
              // #region agent log
              const errorText = await response.text().catch(() => '');
              console.error('NWS_WMS_PROXY_ERROR', JSON.stringify({status:response.status,statusText:response.statusText,errorText:errorText.substring(0,200),targetUrl:targetUrl}));
              // #endregion
              // Return a transparent PNG for errors
              const transparentPng256 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';
              return new Response(Uint8Array.from(atob(transparentPng256), c => c.charCodeAt(0)), {
                status: 200,
                headers: {
                  'Content-Type': 'image/png',
                  'Access-Control-Allow-Origin': '*',
                  'Cache-Control': 'public, max-age=300',
                },
              });
            }
            
            // Get the response data
            const responseData = await response.arrayBuffer();
            
            // Check if response is actually a valid PNG (starts with PNG signature: 89 50 4E 47)
            const pngFirstBytes = Array.from(new Uint8Array(responseData.slice(0, 8)));
            const pngIsValid = pngFirstBytes[0] === 0x89 && pngFirstBytes[1] === 0x50 && pngFirstBytes[2] === 0x4E && pngFirstBytes[3] === 0x47;
            
            // #region agent log
            console.error('NWS_WMS_PROXY_DATA', JSON.stringify({dataSize:responseData.byteLength,contentType:responseContentType,isImage:responseIsImage,isPNG:pngIsValid,firstBytes:pngFirstBytes,targetUrl:targetUrl}));
            // #endregion
            
            // If it's not an image (likely XML error), return transparent PNG
            if (!responseIsImage) {
              // #region agent log
              const textData = new TextDecoder().decode(responseData.slice(0, 500));
              console.error('NWS_WMS_PROXY_NOT_IMAGE', JSON.stringify({contentType:responseContentType,textData:textData,targetUrl:targetUrl}));
              // #endregion
              const transparentPng256 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';
              return new Response(Uint8Array.from(atob(transparentPng256), c => c.charCodeAt(0)), {
                status: 200,
                headers: {
                  'Content-Type': 'image/png',
                  'Access-Control-Allow-Origin': '*',
                  'Cache-Control': 'public, max-age=60',
                },
              });
            }
            
            // If it's not a valid PNG (might be error image or XML), check and log
            if (!pngIsValid && responseData.byteLength > 0) {
              // #region agent log
              const textData = new TextDecoder().decode(responseData.slice(0, 500));
              console.error('NWS_WMS_PROXY_INVALID_PNG', JSON.stringify({contentType:responseContentType,textData:textData,dataSize:responseData.byteLength,targetUrl:targetUrl}));
              // #endregion
              // Return transparent PNG for invalid images
              const transparentPng256 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';
              return new Response(Uint8Array.from(atob(transparentPng256), c => c.charCodeAt(0)), {
                status: 200,
                headers: {
                  'Content-Type': 'image/png',
                  'Access-Control-Allow-Origin': '*',
                  'Cache-Control': 'public, max-age=60',
                },
              });
            }
            
            // Only log small PNGs but don't block them - valid tiles can be small
            // Only block if it's exactly our 68-byte error PNG
            const ourErrorPngSize = 68; // Size of our transparent error PNG
            if (pngIsValid && responseData.byteLength === ourErrorPngSize) {
              // #region agent log
              console.error('NWS_WMS_PROXY_SUSPECTED_ERROR_PNG', JSON.stringify({dataSize:responseData.byteLength,isPNG:pngIsValid,firstBytes:pngFirstBytes,targetUrl:targetUrl}));
              // #endregion
              // This might be our own error PNG being returned - investigate but still pass it through
            } else if (pngIsValid && responseData.byteLength < 200) {
              // Log small but potentially valid PNGs (might be empty/transparent tiles)
              // #region agent log
              console.error('NWS_WMS_PROXY_SMALL_PNG', JSON.stringify({dataSize:responseData.byteLength,isPNG:pngIsValid,firstBytes:pngFirstBytes,targetUrl:targetUrl}));
              // #endregion
            }
            
            // #region agent log
            console.error('NWS_WMS_PROXY_SUCCESS', JSON.stringify({imageDataSize:responseData.byteLength,isPNG:pngIsValid,targetUrl:targetUrl}));
            // #endregion
            
            // Return the image with CORS headers - pass through all valid PNGs regardless of size
            return new Response(responseData, {
              headers: {
                'Content-Type': responseContentType || 'image/png',
                'Access-Control-Allow-Origin': '*',
                'Cache-Control': 'public, max-age=300', // Cache for 5 minutes
              },
            });
          } catch (error) {
            // #region agent log
            console.error('NWS_WMS_PROXY_FETCH_ERROR', JSON.stringify({errorMessage:error.message,errorStack:error.stack,targetUrl:targetUrl}));
            // #endregion
            console.error('NWS WMS proxy error:', error, 'for URL:', targetUrl);
            // Return transparent PNG on error
            const transparentPng256 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';
            return new Response(Uint8Array.from(atob(transparentPng256), c => c.charCodeAt(0)), {
              status: 200,
              headers: {
                'Content-Type': 'image/png',
                'Access-Control-Allow-Origin': '*',
                'Cache-Control': 'public, max-age=60',
              },
            });
          }
        }
        
        if (apiPath.startsWith('reverse')) {
          // Special handling for reverse geocoding (BigDataCloud)
          try {
            const response = await fetch(targetUrl, fetchOptions);
            
            if (!response.ok) {
              const errorText = await response.text();
              console.error(\`Reverse geocoding API error (\${response.status}):\`, errorText.substring(0, 200));
              throw new Error(\`HTTP error! status: \${response.status}\`);
            }
            
            const data = await response.json();
            
            // BigDataCloud returns the data directly, no error field to check
            // Transform to match expected format
            const transformedData = {
              address: {
                city: data.city || data.locality,
                town: data.town,
                village: data.village,
                municipality: data.municipality,
                county: data.county,
                state: data.principalSubdivision,
                state_district: data.principalSubdivision,
                country: data.countryName,
              },
              display_name: data.displayName || \`\${data.city || data.locality || ''}, \${data.principalSubdivision || ''}\`.trim(),
            };
            
            return new Response(JSON.stringify(transformedData), {
              headers: {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*',
              },
            });
          } catch (fetchError) {
            // Re-throw to be caught by outer catch block
            throw fetchError;
          }
        } else {
          // Standard handling for other APIs (forecast, geocoding, etc.)
          try {
            // Create cache key from the full request URL
            const cacheKey = new Request(targetUrl);
            
            // Try to get from cache first (only for forecast and geocoding)
            if (apiPath.startsWith('forecast') || apiPath.startsWith('geocoding')) {
              const cachedResponse = await caches.default.match(cacheKey);
              if (cachedResponse) {
                // Clone the cached response and add CORS headers
                const cachedData = await cachedResponse.json();
                return new Response(JSON.stringify(cachedData), {
                  headers: {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*',
                    'X-Cache': 'HIT',
                  },
                });
              }
            }
            
            // Add timeout for long-running requests (30 seconds)
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), 30000);
            
            if (!fetchOptions) {
              fetchOptions = {};
            }
            fetchOptions.signal = controller.signal;
            
            // Add User-Agent header for Open-Meteo to help with rate limiting
            if (apiPath.startsWith('forecast') || apiPath.startsWith('geocoding')) {
              if (!fetchOptions.headers) {
                fetchOptions.headers = new Headers();
              }
              // Use a descriptive User-Agent to help Open-Meteo identify the app
              fetchOptions.headers.set('User-Agent', 'WeatherApp/1.0 (https://weather-app.jackanglim3.workers.dev)');
            }
            
            // Retry logic for rate limits (max 2 retries)
            let response;
            let retries = 0;
            const maxRetries = 2;
            
            while (retries <= maxRetries) {
              response = await fetch(targetUrl, fetchOptions);
              
              // If we get a 429, check for Retry-After header and wait accordingly
              if (response.status === 429 && retries < maxRetries) {
                const retryAfter = response.headers.get('Retry-After');
                const waitTime = retryAfter 
                  ? parseInt(retryAfter, 10) * 1000 
                  : Math.pow(2, retries) * 1000; // 1s, 2s, 4s
                console.log(\`Rate limited, retrying in \${waitTime}ms... (attempt \${retries + 1}/\${maxRetries})\`);
                await new Promise(resolve => setTimeout(resolve, Math.min(waitTime, 10000))); // Max 10s wait
                retries++;
                continue;
              }
              
              break; // Success or non-retryable error
            }
            
            clearTimeout(timeoutId);
            
            // Handle rate limiting (429) after retries exhausted
            if (response.status === 429) {
              // Check for Retry-After header to provide specific wait time
              const retryAfter = response.headers.get('Retry-After');
              let waitMessage = 'Rate limit exceeded. ';
              if (retryAfter) {
                const waitSeconds = parseInt(retryAfter, 10);
                const waitMinutes = Math.ceil(waitSeconds / 60);
                waitMessage += \`Please wait \${waitMinutes} minute\${waitMinutes > 1 ? 's' : ''} and try again.\`;
              } else {
                waitMessage += 'Please wait 1-2 minutes and try again.';
              }
              
              return new Response(JSON.stringify({ 
                error: true, 
                reason: waitMessage
              }), {
                status: 429,
                headers: {
                  'Content-Type': 'application/json',
                  'Access-Control-Allow-Origin': '*',
                },
              });
            }
            
            if (!response.ok) {
              const errorText = await response.text();
              console.error(\`API error (\${response.status}) for \${targetUrl}:\`, errorText.substring(0, 200));
              throw new Error(\`HTTP error! status: \${response.status}\`);
            }
            
            // Try to parse as JSON
            let data;
            let text;
            try {
              text = await response.text();
              // Check if response is empty
              if (!text || text.trim().length === 0) {
                throw new Error('Empty response from API');
              }
              data = JSON.parse(text);
            } catch (parseError) {
              const contentType = response.headers.get('content-type');
              console.error('Failed to parse JSON response. Content-Type:', contentType, 'Response preview:', text?.substring(0, 200));
              
              // If we got a 429 but it's not JSON, return a proper error
              if (response.status === 429) {
                return new Response(JSON.stringify({ 
                  error: true, 
                  reason: 'Rate limit exceeded. Please try again in a few moments.' 
                }), {
                  status: 429,
                  headers: {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*',
                  },
                });
              }
              
              throw new Error(\`Invalid response format: \${parseError.message}\`);
            }
            
            // Cache successful responses (only for forecast and geocoding)
            if (apiPath.startsWith('forecast') || apiPath.startsWith('geocoding')) {
              // Determine cache duration based on API type
              const cacheSeconds = apiPath.startsWith('forecast') ? 600 : 3600; // 10 min for forecast, 1 hour for geocoding
              
              // Create a response with cache headers
              const cacheResponse = new Response(JSON.stringify(data), {
                headers: {
                  'Content-Type': 'application/json',
                  'Cache-Control': \`public, max-age=\${cacheSeconds}\`,
                },
              });
              
              // Store in cache
              ctx.waitUntil(caches.default.put(cacheKey, cacheResponse.clone()));
            }
            
            return new Response(JSON.stringify(data), {
              headers: {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*',
                'X-Cache': 'MISS',
              },
            });
          } catch (fetchError) {
            if (fetchError.name === 'AbortError') {
              console.error('Request timeout for', targetUrl);
              throw new Error('Request timeout');
            }
            console.error('Fetch error for', targetUrl, ':', fetchError.message);
            throw fetchError;
          }
        }
      } catch (error) {
        console.error('API proxy error:', error);
        return new Response(JSON.stringify({ error: true, reason: error.message }), {
          status: 500,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
          },
        });
      }
    }
    
    // Proxy Ventusky iframe with desktop user agent to remove mobile download button
    if (url.pathname.startsWith('/ventusky-proxy')) {
      try {
        // Extract Ventusky path and parameters
        // Remove /ventusky-proxy prefix to get the Ventusky path (e.g., /precipitation-map)
        const ventuskyPath = url.pathname.replace('/ventusky-proxy', '') || '/precipitation-map';
        const ventuskyParams = url.search;
        const ventuskyUrl = \`https://www.ventusky.com\${ventuskyPath}\${ventuskyParams}\`;
        
        // Fetch with desktop user agent to get desktop version (no download button)
        const response = await fetch(ventuskyUrl, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.9',
          },
        });
        
        if (!response.ok) {
          return new Response('Failed to load Ventusky', { status: response.status });
        }
        
        // Get the HTML content
        let html = await response.text();
        
        // Inject CSS and JavaScript to hide download button
        const hideButtonScript = \`
          <style>
            /* Hide download app button */
            a[href*="app"], 
            button[class*="app"],
            div[class*="app-button"],
            div[class*="download"],
            a[class*="download"],
            button[class*="download"],
            [data-app-button],
            [id*="app-button"],
            [id*="download-button"] {
              display: none !important;
              visibility: hidden !important;
              opacity: 0 !important;
              height: 0 !important;
              width: 0 !important;
              overflow: hidden !important;
            }
          </style>
          <script>
            // Additional JavaScript to hide button after page loads
            (function() {
              function hideDownloadButton() {
                const selectors = [
                  'a[href*="app"]',
                  'button[class*="app"]',
                  'div[class*="app-button"]',
                  'div[class*="download"]',
                  'a[class*="download"]',
                  'button[class*="download"]',
                  '[data-app-button]',
                  '[id*="app-button"]',
                  '[id*="download-button"]'
                ];
                selectors.forEach(selector => {
                  document.querySelectorAll(selector).forEach(el => {
                    el.style.display = 'none';
                    el.style.visibility = 'hidden';
                    el.style.opacity = '0';
                    el.style.height = '0';
                    el.style.width = '0';
                  });
                });
              }
              // Run immediately and on various events
              hideDownloadButton();
              if (document.readyState === 'loading') {
                document.addEventListener('DOMContentLoaded', hideDownloadButton);
              }
              window.addEventListener('load', hideDownloadButton);
              // Use MutationObserver to catch dynamically added buttons
              const observer = new MutationObserver(hideDownloadButton);
              observer.observe(document.body, { childList: true, subtree: true });
              // Also run periodically as fallback
              setInterval(hideDownloadButton, 1000);
            })();
          </script>
        \`;
        
        // Inject framebreaker-neutralizer at the very start of <head>, before any Ventusky scripts run.
        // Ventusky has a framebuster that sets top.location — this overrides window.top/parent
        // so the iframe thinks it IS the top-level window and never fires the redirect.
        const framebreakerScript = \`<script>
          (function() {
            try { Object.defineProperty(window, 'top', { get: function() { return window; } }); } catch(e) {}
            try { Object.defineProperty(window, 'parent', { get: function() { return window; } }); } catch(e) {}
            try { Object.defineProperty(window, 'frameElement', { get: function() { return null; } }); } catch(e) {}
          })();
        </script>\`;
        if (html.includes('<head>')) {
          html = html.replace('<head>', '<head>' + framebreakerScript);
        } else if (html.includes('<head ')) {
          html = html.replace(/<head([^>]*)>/, '<head$1>' + framebreakerScript);
        }

        // Inject button-hiding CSS/JS before closing </head>
        if (html.includes('</head>')) {
          html = html.replace('</head>', hideButtonScript + '</head>');
        } else if (html.includes('<body')) {
          html = html.replace('<body', hideButtonScript + '<body');
        } else {
          html = hideButtonScript + html;
        }
        
        // Return modified HTML with proper headers
        return new Response(html, {
          headers: {
            'Content-Type': 'text/html;charset=UTF-8',
            'X-Frame-Options': 'ALLOWALL',
            'Content-Security-Policy': "frame-ancestors *;",
          },
        });
      } catch (error) {
        console.error('Ventusky proxy error:', error);
        return new Response('Error proxying Ventusky', { status: 500 });
      }
    }
    
    return new Response('Not Found', { status: 404 });
  },
};
`;

// Write the built worker file
fs.writeFileSync(path.join(__dirname, 'src', 'index.js'), workerContent);
console.log('Build complete! Generated src/index.js');

